import type {
  AuthorJobProgressSnapshot,
  AuthorLoadingCard,
  AuthorPreviewResponse,
  PlayControlAction,
  PlaySessionHistoryResponse,
  PlaySessionSnapshot,
} from "../../index"

export const CONCEPT_REVIEW_WORLD = {
  seed:
    "并购签字前夜，她被上司、旧爱和握着黑账的人同时逼到必须站队；只要一句话说错，董事会、关系和体面会一起塌。",
  preview: {
    preview_id: "concept-preview-001",
    prompt_seed:
      "并购签字前夜，她被上司、旧爱和握着黑账的人同时逼到必须站队；只要一句话说错，董事会、关系和体面会一起塌。",
    play_length_preset: "15_20",
    normalized_seed: {
      accepted_shell: "office_power",
      fit_mode: "direct_fit",
      relationship_hook: "升职、旧情和黑账让每一句示好都像勒索。",
      secret_hook: "那份并购补充协议里，藏着一段谁都不敢公开承认的旧关系。",
      surface_signal_ids: ["boardroom", "merger", "audit", "glass_wall"],
      surface_signal_summary: "董事会、并购、法务复核与深夜玻璃墙构成这份故事的高压表层。",
      target_visibility_summary: "适合在半公开、强站队压力的都市场域里推进关系失控。",
      rewritten_seed:
        "并购签字前夜，她被上司、旧爱和握着黑账的人同时逼到必须站队；只要一句话说错，董事会、关系和体面会一起塌。",
      rewrite_reason: "concept_review_seed_lock",
    },
    story_shell_id: "office_power",
    relationship_hook: "升职、旧情和黑账让每一句示好都像勒索。",
    secret_hook: "那份并购补充协议里，藏着一段谁都不敢公开承认的旧关系。",
    surface_signal_ids: ["boardroom", "merger", "audit", "glass_wall"],
    surface_signal_summary: "董事会、并购、法务复核与深夜玻璃墙构成这份故事的高压表层。",
    target_visibility_summary: "适合在半公开、强站队压力的都市场域里推进关系失控。",
    focused_brief: {
      story_kernel: "并购签字前夜的高压站队局。",
      setting_signal: "玻璃会议室、签字夜、法务复核、私密旧情。",
      core_conflict: "主角必须在权力、亲密与自保之间先保一个。",
      tone_signal: "高级都市关系悬疑",
      hard_constraints: [],
      forbidden_tones: [],
    },
    theme: {
      primary_theme: "office_power",
      modifiers: ["15_20", "female"],
      router_reason: "concept_review_story_shell",
    },
    strategies: {
      story_frame_strategy: "relationship_drama_v2",
      cast_strategy: "triangle_plus_pressure_ring",
      beat_plan_strategy: "private_public_escalation",
    },
    structure: {
      cast_topology: "four_route_ring",
      expected_npc_count: 4,
      expected_beat_count: 5,
    },
    story: {
      title: "落地窗之后，没有人只在谈并购",
      premise:
        "签字夜里，所有人都说自己在谈公司，可每一句试探都更像在逼她先承认谁值得被保住。",
      tone: "都市高压关系戏",
      stakes: "一旦黑账和旧关系同时见光，这场并购会立刻从交易变成公开处刑。",
      route_fantasy: "在权力、暧昧和背刺之间选边站队，把一场董事会前夜玩成关系修罗场。",
    },
    cast_slots: [
      { slot_label: "沈知微", public_role: "被推上签字位的执行负责人" },
      { slot_label: "陆衍", public_role: "明面上最稳、私下最危险的旧同盟" },
      { slot_label: "陈维", public_role: "手里捏着补充协议的人，也是最会逼人失态的对手" },
      { slot_label: "程岚", public_role: "只用一句话就能改整个会议室风向的董事会代表" },
    ],
    beats: [
      { title: "门外寒暄", goal: "先看清今晚谁想让你先说破关系。", milestone_kind: "probe" },
      { title: "玻璃墙边", goal: "把那份不能公开的旧同盟重新拽回桌边。", milestone_kind: "alignment" },
      { title: "法务复核", goal: "逼黑账线索先露一角，但不能先让自己翻车。", milestone_kind: "reveal" },
      { title: "主桌站队", goal: "在公开场合先保一个人，也先得罪一个人。", milestone_kind: "commitment" },
      { title: "签字前夜", goal: "决定谁能带着筹码离场，谁要独自背锅。", milestone_kind: "fallout" },
    ],
    flashcards: [
      { card_id: "theme", kind: "stable", label: "题材", value: "董事会修罗场" },
      { card_id: "tone", kind: "stable", label: "气质", value: "高级都市关系悬疑" },
      { card_id: "route_fantasy", kind: "draft", label: "路线幻想", value: "暧昧站队、旧爱回潮、黑账逼供" },
      { card_id: "relationship_hook", kind: "draft", label: "关系钩子", value: "越像护你的人，越可能逼你先认输。" },
      { card_id: "secret_hook", kind: "draft", label: "秘密引线", value: "补充协议和旧关系绑定在一起，谁翻出来谁先流血。" },
    ],
    stage: "brief_locked",
  } satisfies AuthorPreviewResponse,
  loadingCards: [
    { card_id: "theme", emphasis: "stable", label: "题材锁定", value: "董事会修罗场" },
    { card_id: "structure", emphasis: "stable", label: "关系几何", value: "四人权力环" },
    { card_id: "working_title", emphasis: "draft", label: "暂定标题", value: "落地窗之后，没有人只在谈并购" },
    { card_id: "tone", emphasis: "stable", label: "戏剧气压", value: "高级都市关系悬疑" },
    { card_id: "story_premise", emphasis: "draft", label: "前提摘要", value: "签字夜里，所有人都想逼她先承认要保谁。" },
    { card_id: "story_stakes", emphasis: "draft", label: "引爆代价", value: "黑账与旧关系同时见光，交易会变成公开处刑。" },
    { card_id: "cast_count", emphasis: "stable", label: "角色入席", value: "已落位 4 位关键角色" },
    { card_id: "cast_anchor", emphasis: "draft", label: "核心关系锚", value: "陆衍 · 明面稳，私下最危险的旧同盟" },
    { card_id: "beat_count", emphasis: "stable", label: "场面编排", value: "已排 5 个关键场面" },
    { card_id: "opening_beat", emphasis: "draft", label: "开场场面", value: "门外寒暄：先看清谁在逼你先说破关系。" },
    { card_id: "final_beat", emphasis: "draft", label: "终局场面", value: "签字前夜：决定谁带筹码离场，谁背锅收尾。" },
    { card_id: "generation_status", emphasis: "live", label: "编译状态", value: "结局压力与余波回流已收口" },
    { card_id: "token_budget", emphasis: "live", label: "计算痕迹", value: "3,960 枚词元 · 双端收束完成" },
  ] satisfies AuthorLoadingCard[],
  loadingSnapshot: {
    stage: "compile_endings",
    stage_label: "终局压力与余波回流",
    stage_index: 8,
    stage_total: 8,
    completion_ratio: 1,
    primary_theme: "office_power",
    cast_topology: "four_route_ring",
    expected_npc_count: 4,
    expected_beat_count: 5,
    preview_title: "落地窗之后，没有人只在谈并购",
    preview_premise: "签字夜里，所有人都说自己在谈公司，可每一句试探都更像在逼她先承认谁值得被保住。",
    flashcards: [
      { card_id: "theme", kind: "stable", label: "题材", value: "董事会修罗场" },
      { card_id: "tone", kind: "stable", label: "气质", value: "高级都市关系悬疑" },
      { card_id: "route_fantasy", kind: "draft", label: "路线幻想", value: "暧昧站队、旧爱回潮、黑账逼供" },
      { card_id: "relationship_hook", kind: "draft", label: "关系钩子", value: "越像护你的人，越可能逼你先认输。" },
      { card_id: "secret_hook", kind: "draft", label: "秘密引线", value: "补充协议和旧关系绑定在一起，谁翻出来谁先流血。" },
    ],
    loading_cards: [],
  } satisfies AuthorJobProgressSnapshot,
  playSnapshot: {
    session_id: "concept-play-001",
    story_id: "concept-story-001",
    story_mode: "relationship_drama",
    story_shell_id: "office_power",
    status: "active",
    turn_index: 3,
    beat_index: 2,
    beat_title: "玻璃墙边：没有一句试探是无害的",
    story_title: "落地窗之后，没有人只在谈并购",
    narration:
      "会议室里只剩玻璃上的倒影和没有说完的名字。陆衍站在你身侧，没有碰你，却像已经替你挡住了一轮质问；陈维把那份补充协议推到桌边，只等你承认今晚到底先保谁。",
    protagonist: {
      title: "沈知微",
      mandate: "在签字夜之前，先守住一个人，也先丢掉一个人。",
      identity_summary: "你是被推上签字位的执行负责人，所有人都在看你今晚先站向谁。",
      role_label: "签字席主角",
      core_desire: "别让自己在公开场合先被定性。",
      hidden_risk: "你和陆衍的旧关系一旦被陈维坐实，整场并购会立刻换叙事。",
    },
    feedback: {
      ledgers: {
        success: {
          proof_progress: 2,
          coalition_progress: 1,
          order_progress: 0,
          settlement_progress: 1,
        },
        cost: {
          public_cost: 2,
          relationship_cost: 3,
          procedural_cost: 1,
          coercion_cost: 0,
        },
      },
      last_turn_axis_deltas: {
        public_image: -1,
        secret_exposure: 2,
      },
      last_turn_stance_deltas: {
        board_support: -1,
        old_alliance: 2,
      },
      last_turn_global_deltas: {
        scene_heat: 1,
      },
      last_turn_relationship_deltas: {
        luyan: {
          trust: 2,
          tension: 1,
        },
        chenwei: {
          suspicion: 1,
        },
      },
      last_turn_tags: ["半公开试探", "旧同盟回潮", "证物压场"],
      last_turn_consequences: [
        "陆衍明显偏向了你，整个房间都看见了。",
        "陈维没有追问，但他现在更确定你在隐瞒关系。",
        "桌上的补充协议从文件变成了威胁。",
      ],
      last_turn_revealed_secret_ids: ["annex_clause", "private_contact_log"],
    },
    progress: {
      completed_beats: 1,
      total_beats: 5,
      current_beat_progress: 2,
      current_beat_goal: 3,
      turn_index: 3,
      max_turns: 8,
      completion_ratio: 0.35,
      display_percent: 35,
    },
    support_surfaces: {
      inventory: {
        enabled: false,
        disabled_reason: "本轮 concept review 不展示道具背包，焦点只放在关系与余波。",
      },
      map: {
        enabled: false,
        disabled_reason: "本轮 concept review 不展示地图，焦点只放在场面与站队。",
      },
    },
    state_bars: [
      { bar_id: "scene_heat", label: "场面热度", category: "global", current_value: 4, min_value: 0, max_value: 6 },
      { bar_id: "public_image", label: "公众风评", category: "global", current_value: 2, min_value: -3, max_value: 6 },
      { bar_id: "secret_exposure", label: "秘密暴露", category: "global", current_value: 3, min_value: 0, max_value: 6 },
      { bar_id: "luyan-affection", label: "陆衍·亲密", category: "relationship", current_value: 4, min_value: -3, max_value: 6 },
      { bar_id: "luyan-trust", label: "陆衍·信任", category: "relationship", current_value: 5, min_value: -3, max_value: 6 },
      { bar_id: "luyan-tension", label: "陆衍·拉扯", category: "relationship", current_value: 4, min_value: 0, max_value: 6 },
      { bar_id: "chenwei-suspicion", label: "陈维·怀疑", category: "relationship", current_value: 4, min_value: 0, max_value: 6 },
    ],
    current_route_target_id: "luyan",
    relationship_state: {
      scene_heat: 4,
      public_image: 2,
      secret_exposure: 3,
      route_lock: 2,
      current_route_target_id: "luyan",
      targets: [
        {
          character_id: "luyan",
          name: "陆衍",
          affection: 4,
          trust: 5,
          tension: 4,
          suspicion: 1,
          dependency: 2,
          is_route_focus: true,
        },
        {
          character_id: "chenwei",
          name: "陈维",
          affection: 0,
          trust: -1,
          tension: 3,
          suspicion: 4,
          dependency: 0,
          is_route_focus: false,
        },
        {
          character_id: "chenglan",
          name: "程岚",
          affection: 1,
          trust: 2,
          tension: 2,
          suspicion: 2,
          dependency: 1,
          is_route_focus: false,
        },
      ],
    },
    suggested_actions: [
      { suggestion_id: "align-luyan", action_type: "story", label: "先让陆衍替你挡一轮", prompt: "你低声让陆衍先接住这轮追问，把注意力从你身上挪开。" },
      { suggestion_id: "call-chenwei", action_type: "story", label: "当场反问陈维想换什么", prompt: "你盯着陈维，逼他把这份协议真正想换的筹码说出口。" },
      { suggestion_id: "freeze-room", action_type: "story", label: "把会议室先压冷下来", prompt: "你先收住情绪，只点出程序风险，让所有人不敢继续起哄。" },
    ],
    story_actions: [
      { suggestion_id: "align-luyan", action_type: "story", label: "借旧同盟先挡刀", prompt: "把陆衍推到你这一侧，让整个房间先误判你们还是同一阵线。" },
      { suggestion_id: "call-chenwei", action_type: "story", label: "逼陈维先亮底牌", prompt: "反问陈维到底想保谁，让威胁从暗处转到台面上。" },
      { suggestion_id: "name-the-price", action_type: "story", label: "直接开口谈代价", prompt: "先承认今晚有人要被牺牲，但不让别人决定是谁。" },
    ],
    control_actions: [
      {
        action_id: "detonate-annex",
        action_type: "detonate",
        target_mode: "event",
        target_kind: "secret_pressure",
        target_id: "annex_clause",
        label: "引爆补充协议",
        prompt: "现在就让补充协议见光，把这场试探直接抬成公开站队。",
      },
      {
        action_id: "redirect-wave",
        action_type: "redirect",
        target_mode: "kind",
        target_kind: "public_wave",
        target_id: "glass_wall_whisper",
        label: "改写风向",
        prompt: "先把房间里的风向改成程序问题，而不是你的私事。",
      },
    ] satisfies PlayControlAction[],
    latent_radar: [
      { kind: "relationship_debt", pressure: 82, trend: "rising", note: "旧同盟被看见得越多，代价越快回流。" },
      { kind: "secret_pressure", pressure: 76, trend: "triggered", note: "补充协议已经从证物变成了倒计时。" },
      { kind: "public_wave", pressure: 58, trend: "steady", note: "只要再有人开口，半公开场面就会真正失控。" },
    ],
    ending: null,
  } satisfies PlaySessionSnapshot,
  playHistory: {
    session_id: "concept-play-001",
    story_id: "concept-story-001",
    entries: [
      {
        speaker: "gm",
        text: "你走进签字夜之前的玻璃会议室，所有人都装得像只是在等法务版本。",
        created_at: "2026-04-06T06:31:00Z",
        turn_index: 0,
      },
      {
        speaker: "player",
        text: "我先不坐下，直接问陈维是不是想让我先认输。",
        created_at: "2026-04-06T06:32:40Z",
        turn_index: 1,
      },
      {
        speaker: "gm",
        text: "陈维没有否认，只是把补充协议往你面前推近半寸，像是提醒你今晚不只一件事会见光。",
        created_at: "2026-04-06T06:33:00Z",
        turn_index: 1,
      },
      {
        speaker: "player",
        text: "我让陆衍先替我挡一下，先别让程岚看出我乱了。",
        created_at: "2026-04-06T06:35:20Z",
        turn_index: 2,
      },
      {
        speaker: "gm",
        text: "陆衍抬眼接住了那轮质问，程岚没说话，但她已经记下了你们之间那一秒过于熟悉的停顿。",
        created_at: "2026-04-06T06:35:46Z",
        turn_index: 2,
      },
    ],
  } satisfies PlaySessionHistoryResponse,
} as const
